# The make blocks of README.md, extracted beside this by the smoke.readme target, and the value each one promises.
include examples.mk

readme: check
	$(if $(filter awk,$(.FEATURES)),test "$(shout)" = "HELLO")
	$(if $(filter awk,$(.FEATURES)),test "$(head)" = "hell")
	$(if $(filter awk,$(.FEATURES)),test "$(pair)" = "a-b")
	$(if $(filter awk,$(.FEATURES)),test "$(second)" = "beta")
	$(if $(filter awk,$(.FEATURES)),test "$(pct)" = "37.5")
	$(if $(filter awk,$(.FEATURES)),test "$(longest)" = "portable")
	$(if $(filter jq,$(.FEATURES)),test "$(pkg.version)" = "1.2.3")
	$(if $(filter jq,$(.FEATURES)),test '$(strip $(frame))' = 'k/a k/b|')
	$(if $(filter lua,$(.FEATURES)),test "$(answer.lua)" = "42")
	$(if $(filter lua,$(.FEATURES)),test "$(count)" = "9")
	$(if $(filter s7,$(.FEATURES)),test "$(answer.s7)" = "42")
	$(if $(filter s7,$(.FEATURES)),test "$(big)" = "2432902008176640000")
	$(if $(filter lua,$(.FEATURES)),test "$$($(MAKE) -s -f ../../readme.mk greet)" = "hello from Lua 5.4")
	$(if $(filter s7,$(.FEATURES)),test "$$($(MAKE) -s -f ../../readme.mk answer)" = "42")
	$(if $(filter micropy,$(.FEATURES)),test "$(answer.py)" = "7")
	$(if $(filter micropy,$(.FEATURES)),test "$(top)" = "bob")
	$(if $(filter js,$(.FEATURES)),test "$(answer.js)" = "42")
	$(if $(filter js,$(.FEATURES)),test "$(newest)" = "cmk")
	$(if $(filter lua,$(.FEATURES)),test "$(strip $(seen))" = "clang -O2 3")
	$(if $(filter micropy,$(.FEATURES)),test "$(now)" = "-O2 -g")
	$(if $(filter lua,$(.FEATURES)),test "$(loud)" = "HELLO")
	$(if $(filter lua,$(.FEATURES)),test "$(joined)" = "A+B")
	$(if $(filter micropy,$(.FEATURES)),test "$(built)" = "cc debug flags shorten targets.app targets.lib")
	$(if $(filter micropy,$(.FEATURES)),test "$(summary)" = "clang -O2 -Wall true lib: core c")
	$(if $(filter jq,$(.FEATURES)),test "$(version)" = "1.2.3")
	$(if $(filter jq,$(.FEATURES)),test "$(pop)" = "3")
	$(if $(filter jq,$(.FEATURES)),test "$(depth)" = "2")
	$(if $(filter jq,$(.FEATURES)),test "$(who)" = "a b")
	$(if $(filter wasm,$(.FEATURES)),test "$(echoed)" = "Args: test.wasm; hello;")
	$(if $(filter wasm,$(.FEATURES)),test "$(strip $(fibs))" = "55 6765 832040")
	echo "readme: every example holds"
