#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# ///
"""Section-header art for the README, and a lab page that sets header layouts side by side.

Usage: headers.py SPEC OUTDIR LAB. SPEC is a toml list of headers, each an id, a title,
and its links; OUTDIR receives a light and a dark svg per title, per link, and one rule;
LAB is a markdown page showing every header in each layout.
"""

import os
import sys
import tomllib
from html import escape
from pathlib import Path

FONT = "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif"
THEMES = {
  "": {"fg": "#1f2328", "link": "#0969da", "fill": "#f6f8fa", "edge": "#d1d9e0"},
  ".dark": {"fg": "#f0f6fc", "link": "#4493f8", "fill": "#151b23", "edge": "#3d444d"},
}
EM = {**dict.fromkeys("iljtf.,:;!|' ", 0.3), **dict.fromkeys("mwMW", 0.85)}
ROW = 40


def text_width(text, size):
  return sum(EM.get(c, 0.68 if c.isupper() else 0.55) for c in text) * size


def svg(w, h, body, stretch=False):
  ratio = ' preserveAspectRatio="none"' if stretch else ""
  return f'<svg xmlns="http://www.w3.org/2000/svg" width="{w:.0f}" height="{h}" viewBox="0 0 {w:.0f} {h}"{ratio}>{body}</svg>\n'


def title_svg(text, t):
  # Natural spacing, with room to spare: the estimate is rough and empty width on the right is invisible.
  size = 24
  w = text_width(text, size) * 1.15
  return svg(w, ROW, f'<text x="0" y="29" font-family="{FONT}" font-size="{size}" font-weight="600" '
                     f'fill="{t["fg"]}">{escape(text)}</text>')


def button_svg(text, t):
  size, pad, gap = 13, 10, 3
  w = text_width(text, size)
  return svg(w + 2 * pad + 2 * gap, ROW,
             f'<rect x="{gap}" y="8.5" width="{w + 2 * pad:.0f}" height="24" rx="12" fill="{t["fill"]}" stroke="{t["edge"]}"/>'
             f'<text x="{gap + pad}" y="25" font-family="{FONT}" font-size="{size}" fill="{t["link"]}" '
             f'textLength="{w:.0f}" lengthAdjust="spacingAndGlyphs">{escape(text)}</text>')


def rule_svg(t):
  return svg(2000, 1, f'<rect width="2000" height="1" fill="{t["edge"]}"/>', stretch=True)


def picture(src, alt, attrs=""):
  dark = src.replace(".svg", ".dark.svg")
  return (f'<picture><source media="(prefers-color-scheme: dark)" srcset="{dark}">'
          f'<img{attrs} src="{src}" alt="{escape(alt)}"></picture>')


def emit(outdir, name, make):
  for suffix, theme in THEMES.items():
    (outdir / f"{name}{suffix}.svg").write_text(make(theme))


def lab_href(href):
  # The spec names README targets; the lab page sits in docs/ beside FFI.md.
  if href.startswith("#"):
    return "../README.md" + href
  return href.removeprefix("docs/")


def spacer_table(h, img):
  links = " | ".join(f'<a href="{lab_href(u)}">{escape(t)}</a>' for t, u in h["links"])
  return "\n".join([
    '<table width="100%">', "  <tr>",
    f'    <td nowrap><h3>{escape(h["title"])}</h3></td>',
    f'    <td align=right><img align=right width=2000 height=0 alt="" src="{os.path.dirname(img)}/icon.svg">{links}</td>',
    "  </tr>", "</table>"])


def svg_float(h, img):
  title = f'<a href="{lab_href("#" + h["id"])}">{picture(f"{img}/{h["id"]}.title.svg", h["title"], " align=left")}</a>'
  # Inline buttons in a right-aligned paragraph wrap in reading order, where right floats would stack reversed.
  buttons = "".join(
    f'<a href="{lab_href(u)}">{picture(f"{img}/{h["id"]}.{i}.svg", t)}</a>'
    for i, (t, u) in enumerate(h["links"]))
  rule = picture(f"{img}/rule.svg", "", " width=2000 height=1")
  return f'<p align="right">{title}{buttons}</p>\n<br clear="all">\n{rule}'


def plain(h, img):
  links = " | ".join(f'<a href="{lab_href(u)}">{escape(t)}</a>' for t, u in h["links"])
  return f'### {h["title"]}\n<p align="right">{links}</p>'


VARIANTS = [
  ("v1", "Spacer table", "the README's current form: a two-cell table stretched by a zero-height image", spacer_table),
  ("v2", "SVG float", "a title svg floated left, a button svg per link floated right, a clear, then a one-pixel rule stretched like the spacer", svg_float),
  ("v3", "Plain", "a markdown heading and a right-aligned paragraph of links under it", plain),
]


def lab(headers, img):
  out = ["# Header lab", "",
         "Generated by `make docs.headers` from [headers.toml](headers.toml); edit the spec, not this page.", "",
         "| # | layout | what it is |", "| --- | --- | --- |"]
  out += [f"| {k.upper()} | [{name}](#{k}) | {what} |" for k, name, what, _ in VARIANTS]
  for k, name, _, render in VARIANTS:
    out += ["", f'<a id="{k}"></a>', "", f"## {k.upper()}: {name}", ""]
    for h in headers:
      out += [render(h, img), "", "Body text under the header, so the spacing to the next paragraph shows.", ""]
  return "\n".join(out) + "\n"


def main(spec, outdir, labpath):
  headers = tomllib.loads(Path(spec).read_text())["header"]
  outdir, labpath = Path(outdir), Path(labpath)
  outdir.mkdir(parents=True, exist_ok=True)
  emit(outdir, "rule", rule_svg)
  for h in headers:
    emit(outdir, f'{h["id"]}.title', lambda t, h=h: title_svg(h["title"], t))
    for i, (text, _) in enumerate(h["links"]):
      emit(outdir, f'{h["id"]}.{i}', lambda t, text=text: button_svg(text, t))
  img = os.path.relpath(outdir, labpath.parent)
  labpath.write_text(lab(headers, img))
  print(f"{len(headers)} headers: svgs in {outdir}, lab at {labpath}")


if __name__ == "__main__":
  if len(sys.argv) != 4:
    sys.exit(__doc__)
  main(*sys.argv[1:])
