# via/amk/demos/meta-1.mk: a Scheme macro writes make rules, and eval feeds them back to the parser.
.RECIPEPREFIX := >

# Stock make's feature list carries no engine word, so this demo stops before it reaches s7.
ifeq ($(filter s7,$(.FEATURES)),)
  $(error $(lastword $(MAKEFILE_LIST)) needs amk with s7 -- run it as ./amk -f $(lastword $(MAKEFILE_LIST)), not under stock make)
endif

# The generator: one macro that prints a rule, and a loop that stamps it for every name.
define s7.greeters
(define-macro (rule name . cmds)
  `(begin
     (format #t "~A: ~%" ,name)
     (for-each (lambda (c) (format #t ">echo ~A~%" c)) (list ,@cmds))
     (format #t "greeters += ~A~%" ,name)))
(for-each
  (lambda (n)
    (rule (string-append "greet." n)
          (string-append "hello from " n)
          (string-append "generated by " (*s7* 'version))))
  (list "alpha" "beta" "gamma"))
endef

greeters :=
generated := $(s7 ${s7.greeters})
$(eval $(generated))

__main__: $(greeters)
> echo "generated targets: $(greeters)"

# Print the code the macro wrote, without running it.
show:
> $(info $(generated))
